const STRATEGY_DATA = {
  "generated_at": "2026-06-06T06:00:34+09:00",
  "market_update": "US 06/05 16:00 EDT | KST 06/06 05:00",
  "market": {
    "ultra_analysis": "AVGO(브로드컴) AI 매출 전망 실망이 반도체 섹터 전체 매도 촉발. 5월 고용 172,000명 서프라이즈로 금리인하 기대 후퇴. S&P 500 9주 연속 상승 streak 종료 임박. 시장 전반 리스크오프 모드. 월요일 추가 갭다운 예상되나, 금요일 한국장 이미 -5~10% 폭락해 일부 충격 선반영.",
    "ultra_action": "관망 (일부 딥바잉 기회 모색)",
    "hermes_deepseek": "AVGO CEO Hock Tan 발언이 버블 신호로 해석된 점은 동의. SOXL -24%는 3X 레버리지 상품 특성상 과장된 움직임. 기초 반도체 지수는 -8% 내외. 유가 92.90(-2.24%) 하락은 경기 둔화 우려 확장 의미. VIX 19.12(아직 30未)=아직 패닉 단계 아님. 질서 있는 조정. 한국장 금요일 -5~10% 선반영으로 추가 하락분 제한적."
  },
  "stocks": [
    {
      "name": "주성엔지니어링",
      "ticker": "036930",
      "category": "장비",
      "price": 210000,
      "change": -16.17,
      "rsi": 50.0,
      "support_1": 190000,
      "support_2": 180500,
      "resistance_1": 223000,
      "resistance_2": 234000,
      "volume_ratio": 1.0,
      "volume": 2844075,
      "sma_5": 199500,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "AVGO 충격에 장비주 대표로 -16% 폭락. -16%는 극단적 낙폭. 190,000선 지지 여부가 관건. 월요일 추가 하락 시 180,500까지 하방 열림.",
        "action": "관망 (바닥 확인 후)",
        "entry": "190,000~200,000",
        "target": "223,000",
        "stop": "185,000",
        "reasoning": "-16% 폭락. AVGO 충격 후 바닥 확인 필요.",
        "elo": {
          "score": 1100,
          "wins": 1,
          "losses": 3,
          "total": 4,
          "accuracy": "25.0%",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "-16%는 과도한 낙폭이지만 AVGO 충격이 장비주 전체 타격. 190,000선 이탈 시 180,500까지 추가 하락 가능. 바닥 확인이 우선.",
        "risk": "AVGO 충격으로 월요일 추가 하락 가능.",
        "supplement": "장비주 5형제 중 최대 낙폭. 반등시 탄력적.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "제주반도체",
      "ticker": "080220",
      "category": "유통",
      "price": 93500,
      "change": -12.86,
      "rsi": 50.0,
      "support_1": 93500,
      "support_2": 88800,
      "resistance_1": 93500,
      "resistance_2": 98200,
      "volume_ratio": 1.0,
      "volume": 1631657,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-12.86% 급락. 낙폭 기준 과매도권. 93,500=1차 지지선. AVGO 충격에 동조화. 유통업 특성상 직접 연관성 낮아 과도한 낙폭.",
        "action": "관망 (바닥 확인 후)",
        "entry": "88,800~93,000",
        "target": "98,200",
        "stop": "87,000",
        "reasoning": "-12.86% 급락. 유통업 과도한 낙폭.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "유통업은 AVGO 충격과 직접적 연관성 낮음. 과도한 낙폭으로 딥바잉 기회 가능. 88,800선 이하 추가 하락시 분할매수.",
        "risk": "거래량 부족으로 회복 속도 느림.",
        "supplement": "유통주는 장비 대비 회복 패턴 다름.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "피에스케이",
      "ticker": "319660",
      "category": "장비",
      "price": 126500,
      "change": 10.58,
      "rsi": 50.0,
      "support_1": 126500,
      "support_2": 120000,
      "resistance_1": 126500,
      "resistance_2": 133000,
      "volume_ratio": 1.0,
      "volume": 1227232,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                                 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 .................................................................................................",
      "ultra": {
        "analysis": "+10.58% 막판까지 강세. RSI 72.3=과매수. 5일 연속 상승. 단기 급등 부담. SOXL -24%로 월요일 75,000선 테스트.",
        "action": "익절(일부)/관망",
        "entry": "-",
        "target": "87,000",
        "stop": "72,000",
        "reasoning": "+10.58%+RSI 72. SOXL 충격에 조정 불가피.",
        "elo": {
          "score": 1380,
          "wins": 5,
          "losses": 1,
          "total": 6,
          "accuracy": "83.3%",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "5일 연속 상승+RSI 72 추격매수 절대 금지(규칙 3). +10.58%면 2~3% 조정받아도 +7%대=여전히 좋은 수익. 익절이 맞는 선택.",
        "risk": "5일 연속 상승+RSI 72+AVGO 충격=3중 리스크.",
        "supplement": "금요일 장비주 5형제는 월요일 '갈아타기' 관점. 오른 건 판다.",
        "agreement": "동의"
      }
    },
    {
      "name": "한화비전",
      "ticker": "489790",
      "category": "보안/반도체장비",
      "price": 71500,
      "change": -10.06,
      "rsi": 50.0,
      "support_1": 71500,
      "support_2": 67900,
      "resistance_1": 71500,
      "resistance_2": 75100,
      "volume_ratio": 1.0,
      "volume": 732037,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-10.06% 동반 하락. 보안+장비 이중 업종 리스크. 낙폭 과대. 71,500 지지선 사수 여부가 관건. 신규 상장 종목으로 변동성 높음.",
        "action": "관망",
        "entry": "67,900~71,500",
        "target": "75,100",
        "stop": "66,000",
        "reasoning": "-10% 폭락. 보안주 특성상 반등시 회복력.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "신규 상장 종목으로 히스토리 부족. AVGO 충격과 무관한 보안 부문은 오히려 방어력 있을 수 있음. 71,500 지지 확인 후 접근.",
        "risk": "신규 상장=변동성 높음. 유동성 리스크.",
        "supplement": "보안주는 반도체 대비 독자적 흐름.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "SK하이닉스",
      "ticker": "000660",
      "category": "대장주",
      "price": 2070000,
      "change": -9.92,
      "rsi": 50.0,
      "support_1": 2150000,
      "support_2": 2042000,
      "resistance_1": 2404000,
      "resistance_2": 2524000,
      "volume_ratio": 1.0,
      "volume": 5778751,
      "sma_5": 2317000,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-9.92% 28개 종목 중 최대 낙폭. RSI 18.5 = 극단적 과매도. HBM/AI 모멘텀에도 AVGO 충격으로 AI주 전체 직격탄. 월요일 160만선 테스트.",
        "action": "관망 (바닥 확인 후 접근)",
        "entry": "155만~160만",
        "target": "185만",
        "stop": "150만",
        "reasoning": "AVGO 충격에 가장 취약한 AI 대장주. RSI 18=6개월래 최저 과매도. 바닥 확인 후 접근.",
        "elo": {
          "score": 1200,
          "wins": 1,
          "losses": 2,
          "total": 3,
          "accuracy": "33.3%",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "-9.92%=1년래 최대 낙폭. AVGO CEO 발언이 AI 반도체 전체 신뢰를 흔든 상황. HBM 프리미엄도 의심받을 수 있음. 155만선 이하 추가 하락 시 기회.",
        "risk": "AI 칩 버블 논쟁이 HBM까지 번질 경우 하이닉이 가장 큰 타격.",
        "supplement": "SOXL -24% = 월요일도 안전하지 않음. 최소 160만선 지지 확인 필요.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "이수페타시스",
      "ticker": "007660",
      "category": "PCB",
      "price": 120900,
      "change": -9.57,
      "rsi": 50.0,
      "support_1": 121000,
      "support_2": 115000,
      "resistance_1": 121000,
      "resistance_2": 127000,
      "volume_ratio": 1.0,
      "volume": 1220122,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-9.57% PCB주 동반 약세. 121,000=지지선이자 현재가. AVGO 충격이 PCB 업종에 간접 영향. 반도체 CapEx 축소시 수주 감소 우려.",
        "action": "관망",
        "entry": "115,000~121,000",
        "target": "127,000",
        "stop": "113,000",
        "reasoning": "PCB주 동반 하락. AVGO 간접 영향.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "PCB는 AI 반도체 수혜주로 분류돼 AVGO 충격에 간접 영향. 121,000선 방어 실패 시 115,000까지 추가 하락. 관망이 안전.",
        "risk": "AI CapEx 축소시 PCB 수주 타격.",
        "supplement": "PCB 업종은 장비 대비 회복 속도 느림.",
        "agreement": "동의"
      }
    },
    {
      "name": "심텍",
      "ticker": "222800",
      "category": "반도체기판",
      "price": 103000,
      "change": -9.17,
      "rsi": 50.0,
      "support_1": 103000,
      "support_2": 97800,
      "resistance_1": 103000,
      "resistance_2": 108000,
      "volume_ratio": 1.0,
      "volume": 1074009,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-9.17% 반도체기판 동반 하락. 103,000=현재가=지지선. AVGO 충격으로 AI 기판 수요 우려. AI 기판은 HBM과 연계된 구조라 직접적 영향.",
        "action": "관망",
        "entry": "97,800~103,000",
        "target": "108,000",
        "stop": "96,000",
        "reasoning": "AI 기판주. AVGO 여파 관망.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "AI 기판은 HBM과 연계된 구조라 AVGO 충격에 직접적. 103,000선 이탈 시 추가 하락 불가피. 바닥 확인 후 접근.",
        "risk": "AI 기판 수요 둔화시 타격 큼.",
        "supplement": "심텍은 실적 대비 저평가. 장기 관점.",
        "agreement": "동의"
      }
    },
    {
      "name": "SFA반도체",
      "ticker": "036540",
      "category": "조립검사",
      "price": 7180,
      "change": -9.0,
      "rsi": 50.0,
      "support_1": 7180,
      "support_2": 6820,
      "resistance_1": 7180,
      "resistance_2": 7540,
      "volume_ratio": 1.0,
      "volume": 2930190,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                 차 분 기 보 고 서............................................................................................................................................1 【 대표이사 등의 확인 】...................................................................................................................",
      "ultra": {
        "analysis": "-9.0% 동반 하락. 조립검사 업종은 AVGO 충격 영향 제한적. 7,180선 지지 여부 확인. 거래량 293만=활발. 바닥권 분할매수 검토.",
        "action": "관망 (딥바잉 검토)",
        "entry": "6,820~7,180",
        "target": "7,540",
        "stop": "6,700",
        "reasoning": "조립검사는 AVGO 직접 타격 적음.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "조립검사는 AVGO와 무관하나 시장 전체 매도에 휩쓸림. 바닥권 분할매수 유효. 6,820선 이하에서 추가 매수.",
        "risk": "시장 전체 약세시 방어력 제한적.",
        "supplement": "저가 매수 관점. 단기 반등 기대.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "두산테스나",
      "ticker": "131970",
      "category": "테스트서비스",
      "price": 135600,
      "change": -8.07,
      "rsi": 50.0,
      "support_1": 138000,
      "support_2": 131000,
      "resistance_1": 161500,
      "resistance_2": 169500,
      "volume_ratio": 1.0,
      "volume": 353949,
      "sma_5": 149500,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-8.07% 동반 하락. Grok 3 수주 루머에도 AVGO 충격에 밀림. CapEx 2,303억 설비투자 유효 호재. RSI 32.8 = 과매도 직전. 14만선 바닥 형성 중.",
        "action": "딥바잉 (루머 확인 후)",
        "entry": "138,000~142,000",
        "target": "160,000",
        "stop": "132,000",
        "reasoning": "CapEx 2,303억+Grok 3 기대=미래가치. 76% 급등 후 조정 국면. 루머 확정시 폭발적 반등.",
        "elo": {
          "score": 1180,
          "wins": 1,
          "losses": 2,
          "total": 3,
          "accuracy": "33.3%",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "AVGO 충격+AI 버블 논란 속 Grok 3 루머는 더 위험. CapEx 2,303억은 부채 증가+감가상각비 증가로 단기 실적 압박 요인. 거래량 28만=관심 부족. Grok 3 공시 확인 후 진입이 안전.",
        "risk": "Grok 3 루머 불발 시 132,000 이하 추락 가능. 거래량 28만=유동성 리스크.",
        "supplement": "차라리 PSK(+10.58%) 조정 때 진입하거나 Grok 3 공시 확인 후 추격.",
        "agreement": "반박"
      }
    },
    {
      "name": "동진쎄미켐",
      "ticker": "005290",
      "category": "소재",
      "price": 54900,
      "change": -8.04,
      "rsi": 50.0,
      "support_1": 51800,
      "support_2": 49200,
      "resistance_1": 55300,
      "resistance_2": 58100,
      "volume_ratio": 1.0,
      "volume": 658267,
      "sma_5": 52800,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-8.04% 소재주 동반 약세. PER 28배 영업이익률 20.3% 밸류에이션 부담 없음. RSI 25.1 극단적 과매도. AVGO 충격이 소재주에 직접 타격 제한적.",
        "action": "딥바잉(분할매수)",
        "entry": "118,000~122,000",
        "target": "135,000",
        "stop": "113,000",
        "reasoning": "과도한 낙폭+견조한 펀더멘탈. AVGO와 무관한 소재주 특성상 반등 시 회복력 기대.",
        "elo": {
          "score": 1280,
          "wins": 3,
          "losses": 1,
          "total": 4,
          "accuracy": "75.0%",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "펀더멘탈은 좋고 RSI 25는 과매도 확실. 문제는 소재주 동반 약세=업종 자체가 안 좋으면 개별 반등 어려움. 장비주가 월요일 조정 들어가면 소재주 추가 하락. 118,000까지 기다림.",
        "risk": "소재주 업종 약세 시 115,000까지 추가 하락. 회복 속도 느림.",
        "supplement": "동진은 장기 보유 무난. 단기 트레이딩 부적합. AVGO 충격 해소 후 접근.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "하나마이크론",
      "ticker": "067310",
      "category": "패키징테스트",
      "price": 41850,
      "change": -7.82,
      "rsi": 50.0,
      "support_1": 41800,
      "support_2": 39800,
      "resistance_1": 41800,
      "resistance_2": 43900,
      "volume_ratio": 1.0,
      "volume": 1000556,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-7.82% 패키징 동반 하락. 41,800=지지선. HBM 후공정 관련주로 AVGO 충격 간접 영향. 낙폭 과대. 실적 모멘텀 확인 후 진입.",
        "action": "관망 (바닥 확인 후)",
        "entry": "39,800~41,800",
        "target": "43,900",
        "stop": "39,000",
        "reasoning": "HBM 후공정주. AVGO 충격 간접 영향.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "HBM 후공정 관련주는 AI 투자 축소시 직접 타격. 41,800선 방어가 중요. 실적 모멘텀 확인 후 진입.",
        "risk": "HBM CapEx 축소시 후공정 수주 감소.",
        "supplement": "동진쎄미켐과 함께 소재/패키징 바닥권.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "고영",
      "ticker": "098460",
      "category": "3D검사",
      "price": 31350,
      "change": -7.52,
      "rsi": 50.0,
      "support_1": 31400,
      "support_2": 29800,
      "resistance_1": 31400,
      "resistance_2": 32900,
      "volume_ratio": 1.0,
      "volume": 1424380,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                 차 분 기 보 고 서............................................................................................................................................1 【 대표이사 등의 확인 】...................................................................................................................",
      "ultra": {
        "analysis": "-7.52% 3D검사 동반 하락. 31,400=지지선. 장비주 전반 약세에 동조화. 반도체 검사 수요와 무관한 낙폭. 과도한 낙폭으로 반등시 탄력 기대.",
        "action": "관망",
        "entry": "29,800~31,400",
        "target": "32,900",
        "stop": "29,000",
        "reasoning": "3D검사 업종. AVGO와 무관한 낙폭.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "3D검사는 AI 반도체와 직접적 연관성 낮음. 과도한 낙폭일 가능성. 31,400선 지지 확인 시 분할매수 기회.",
        "risk": "거래량 대비 호가 스프레드 리스크.",
        "supplement": "고영은 실적 안정적. 바닥권 접근.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "에스에프에이",
      "ticker": "056190",
      "category": "장비",
      "price": 25550,
      "change": -7.26,
      "rsi": 50.0,
      "support_1": 25600,
      "support_2": 24300,
      "resistance_1": 25600,
      "resistance_2": 26800,
      "volume_ratio": 1.0,
      "volume": 113115,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                 차 분 기 보 고 서............................................................................................................................................1 【 대표이사 등의 확인 】...................................................................................................................",
      "ultra": {
        "analysis": "-7.26% 장비주 동반 하락. 25,600=지지선. 거래량 11만=낮음. AVGO 충격에도 관심 부족. 바닥 확인 필요.",
        "action": "관망 (진입 비권장)",
        "entry": "24,300~25,600",
        "target": "26,800",
        "stop": "24,000",
        "reasoning": "거래량 부족+장비주 약세. 진입 비권장.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "거래량 11만=관심 부족. 장비주 반등에도 소외될 가능성. 다른 장비주 대비 매력도 낮음. 관망 추천.",
        "risk": "거래량 부족으로 유동성 리스크.",
        "supplement": "장비주 중 최악의 거래량. 패스.",
        "agreement": "동의"
      }
    },
    {
      "name": "한미반도체",
      "ticker": "042700",
      "category": "장비",
      "price": 283000,
      "change": -6.91,
      "rsi": 50.0,
      "support_1": 275500,
      "support_2": 261500,
      "resistance_1": 296000,
      "resistance_2": 311000,
      "volume_ratio": 1.0,
      "volume": 967822,
      "sma_5": 287500,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-6.91% 장비주 동반 하락. 275,500=1차 지지. TC Bonder 장비 독점. 펀더멘탈 유효. AVGO 충격으로 과도한 낙폭. 조정시 분할매수 기회.",
        "action": "관망 (분할매수 검토)",
        "entry": "261,500~275,500",
        "target": "296,000",
        "stop": "258,000",
        "reasoning": "TC Bonder 독점. 펀더멘탈 견조.",
        "elo": {
          "score": 1220,
          "wins": 2,
          "losses": 2,
          "total": 4,
          "accuracy": "50.0%",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "한미는 TC Bonder 독점으로 AVGO 충격에도 장비 수주 모멘텀 유효. 275,500선 이하 분할매수 나쁘지 않음. 단 하이닉 실적에 민감.",
        "risk": "HBM CapEx 축소시 TC Bonder 수주 차질.",
        "supplement": "TC Bonder 독점=차별화. 조정시 매수.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "이엔에프테크놀로지",
      "ticker": "102710",
      "category": "소재",
      "price": 41900,
      "change": -6.79,
      "rsi": 50.0,
      "support_1": 41900,
      "support_2": 39800,
      "resistance_1": 41900,
      "resistance_2": 44000,
      "volume_ratio": 1.0,
      "volume": 80054,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-6.79% 소재주 동반 약세. 41,900=지지선. 거래량 8만=매우 낮음. AVGO 충격과 무관하나 유동성 부족으로 진입 비권장.",
        "action": "관망 (진입 비권장)",
        "entry": "39,800~41,900",
        "target": "44,000",
        "stop": "39,000",
        "reasoning": "거래량 8만=유동성 리스크.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "소재주이지만 거래량 8만은 심각한 유동성 문제. AVGO 충격과 무관해도 회복 속도 느림. 다른 종목 우선.",
        "risk": "8만 거래량=출구 전략 어려움.",
        "supplement": "소재주 중에서도 비선호. 패스.",
        "agreement": "동의"
      }
    },
    {
      "name": "에스앤에스텍",
      "ticker": "101490",
      "category": "마스크",
      "price": 62300,
      "change": -6.74,
      "rsi": 50.0,
      "support_1": 62300,
      "support_2": 59200,
      "resistance_1": 62300,
      "resistance_2": 65400,
      "volume_ratio": 1.0,
      "volume": 238585,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-6.74% 동반 하락. 62,300=지지선. 마스크 업종은 반도체 투자와 밀접. AVGO 충격으로 신규 팹 투자 지연 가능성.",
        "action": "관망",
        "entry": "59,200~62,300",
        "target": "65,400",
        "stop": "58,000",
        "reasoning": "마스크 업종. AVGO 간접 영향.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "마스크 업종은 반도체 투자와 밀접. AVGO 충격으로 신규 팹 투자 지연 가능성. 62,300선 방어 확인 필요.",
        "risk": "팹 투자 지연시 마스크 수요 감소.",
        "supplement": "블랙홀 기간. 관망이 최선.",
        "agreement": "동의"
      }
    },
    {
      "name": "와이씨",
      "ticker": "232140",
      "category": "장비",
      "price": 14920,
      "change": -6.69,
      "rsi": 50.0,
      "support_1": 14900,
      "support_2": 14200,
      "resistance_1": 14900,
      "resistance_2": 15700,
      "volume_ratio": 1.0,
      "volume": 791019,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-6.69% 장비주 동반 하락. 14,900=지지선. 거래량 79만=활발. 소형 장비주로 변동성 높음. 바닥권 분할매수 검토.",
        "action": "관망 (딥바잉 검토)",
        "entry": "14,200~14,900",
        "target": "15,700",
        "stop": "14,000",
        "reasoning": "소형 장비주. 바닥권 분할매수.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "소형 장비주는 대형주보다 변동성 큼. 14,900선 방어 성공 시 반등 탄력적. 단 AVGO 충격 해소 전까지 신중.",
        "risk": "소형주=유동성 리스크+변동성.",
        "supplement": "와이씨는 실적 모멘텀 확인 후.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "삼성전자",
      "ticker": "005930",
      "category": "대장주",
      "price": 329000,
      "change": -6.4,
      "rsi": 50.0,
      "support_1": 311000,
      "support_2": 295500,
      "resistance_1": 368000,
      "resistance_2": 386500,
      "volume_ratio": 1.0,
      "volume": 33725012,
      "sma_5": 349000,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "거래량 3,372만주 역대급. 외국인/기관 이탈 속 개인 저가매수 유입. RSI 22.3 = 극단적 과매도. 52주 저점 248,000 근접 시 추가 하락 가능. 반등 시 275,000선 1차 저항.",
        "action": "관망 (일부 분할매수 검토)",
        "entry": "255,000 이하",
        "target": "275,000",
        "stop": "245,000",
        "reasoning": "RSI 22의 과매도는 1년에 1~2번 기회. 외인 이탈 속도 고려 바닥 확인 후 진입.",
        "elo": {
          "score": 1250,
          "wins": 2,
          "losses": 1,
          "total": 3,
          "accuracy": "66.7%",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "RSI 22는 역대급 과매도지만 '싸다고 오르는 게 아님'(규칙 1). 거래량 3,372만 = 외인/기관 던지는 물량을 개인이 받는 구조. AVGO 충격으로 월요일 외인 매도 지속 시 255,000도 뚫릴 가능성.",
        "risk": "외인 이탈+AVGO 충격 이중 악재. 바닥 확인 전 분할매수 신중.",
        "supplement": "삼전 PER은 낮지만 고용쇼크로 금리인하 기대 후퇴가 대장주 악재.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "GST",
      "ticker": "083450",
      "category": "검사장비",
      "price": 51700,
      "change": -6.0,
      "rsi": 50.0,
      "support_1": 51700,
      "support_2": 49100,
      "resistance_1": 51700,
      "resistance_2": 54300,
      "volume_ratio": 1.0,
      "volume": 238691,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-6.0% 검사장비 동반 하락. 51,700=지지선. 거래량 24만=낮음. 검사장비는 AI 반도체 퀄 테스트와 직결. 과도한 낙폭.",
        "action": "관망",
        "entry": "49,100~51,700",
        "target": "54,300",
        "stop": "48,000",
        "reasoning": "검사장비. 과도한 낙폭. 관망.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "검사장비는 AI 반도체 퀄 테스트와 직결. AVGO 충격이 오히려 검사 수요 증가 요인. 과도한 낙폭 매수 기회.",
        "risk": "거래량 24만=유동성 부족.",
        "supplement": "검사장비는 반도체 퀄 필수. 수요 지속.",
        "agreement": "반박"
      }
    },
    {
      "name": "HPSP",
      "ticker": "403870",
      "category": "장비",
      "price": 50300,
      "change": 5.89,
      "rsi": 50.0,
      "support_1": 44200,
      "support_2": 41900,
      "resistance_1": 49900,
      "resistance_2": 52400,
      "volume_ratio": 1.0,
      "volume": 9723522,
      "sma_5": 46400,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "+5.89% 2일 연속 강세. 거래량 972만=평균 4.5배 폭발. RSI 68.5 과매수 직전. SOXL -24%가 장비주 심리에 부정적. 월요일 차익실현 리스크.",
        "action": "일부 익절/관망",
        "entry": "-",
        "target": "35,500",
        "stop": "31,500",
        "reasoning": "2일 +12% 급등. RSI 68.5. AVGO 충격에 월요일 조정 예상.",
        "elo": {
          "score": 1350,
          "wins": 4,
          "losses": 1,
          "total": 5,
          "accuracy": "80.0%",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "972만 거래량 폭발 속+5.89%는 강력한 상승. 그러나 금요일 장비주만 강세=월요일 갭다운 시 가장 큰 낙폭 가능. SOXL -24% 충격에 장비주 가장 먼저 매도. 익절이 현명.",
        "risk": "SOXL -24%=월요일 장비주 직격탄. 2일+RSI 68.5=차익실현 리스크 최대.",
        "supplement": "장비주 5형제(PSK, HPSP, 원익IPS, 테스, 유진테크) 전부 월요일 조정 가능.",
        "agreement": "동의"
      }
    },
    {
      "name": "ISC",
      "ticker": "095340",
      "category": "소켓",
      "price": 202000,
      "change": -5.61,
      "rsi": 50.0,
      "support_1": 201500,
      "support_2": 191500,
      "resistance_1": 211500,
      "resistance_2": 222000,
      "volume_ratio": 1.0,
      "volume": 251506,
      "sma_5": 206500,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-5.61% 시장 동조화 하락. 영업이익률 34.6%=리스트 TOP3. 부채비율 16.3%=초우량. 특별 모멘텀 없지만 펀더멘탈 최강. RSI 35 과매도 직전. 6/5 공매도 8.6만주(34.4%) 주의.",
        "action": "관망 (바닥권 분할매수)",
        "entry": "195,000~200,000",
        "target": "215,000",
        "stop": "190,000",
        "reasoning": "펀더멘탈 최상위. 거래량 부족이 단점. 바닥권 분할매수 접근.",
        "elo": {
          "score": 1320,
          "wins": 4,
          "losses": 1,
          "total": 5,
          "accuracy": "80.0%",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "ISC는 두테와 달리 루머 리스크 없음. 펀더멘탈 우량. AVGO 충격으로 월요일 추가 하락 시 오히려 기회. 195,000~200,000 분할매수 괜찮은 전략. 단 공매도 34.4%는 하방 압력.",
        "risk": "공매도 34.4%는 부담. 거래량 17만=유동성 리스크.",
        "supplement": "ISC는 소방차 개념. 다른 종목 폭락할 때 덜 빠짐(-5.61% vs 평균 -6~10%). 방어주 성격.",
        "agreement": "동의"
      }
    },
    {
      "name": "솔브레인",
      "ticker": "357780",
      "category": "소재",
      "price": 363000,
      "change": -5.59,
      "rsi": 50.0,
      "support_1": 363000,
      "support_2": 345000,
      "resistance_1": 363000,
      "resistance_2": 381000,
      "volume_ratio": 1.0,
      "volume": 63867,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-5.59% 소재주 동반 약세. 363,000=지지선. 거래량 6만=매우 낮아 관심 부족. AVGO 충격과 무관하나 유동성 리스크 큼.",
        "action": "관망 (진입 비권장)",
        "entry": "345,000~363,000",
        "target": "381,000",
        "stop": "340,000",
        "reasoning": "소재주. 거래량 부족. 진입 비권장.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "솔브레인은 실적 안정적이나 거래량 6만은 유동성 최악. AVGO 충격 후 회복 속도 느림. 다른 종목 우선.",
        "risk": "6만 거래량=출구 전략 불가.",
        "supplement": "고가 소재주. 관망만 추천.",
        "agreement": "동의"
      }
    },
    {
      "name": "에스티아이",
      "ticker": "039440",
      "category": "장비",
      "price": 28000,
      "change": -5.56,
      "rsi": 50.0,
      "support_1": 28000,
      "support_2": 26600,
      "resistance_1": 28000,
      "resistance_2": 29400,
      "volume_ratio": 1.0,
      "volume": 120359,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-5.56% 장비주 동반 하락. 28,000=지지선. 거래량 12만=낮음. 장비주 중 관심 부족. 바닥 확인 필요.",
        "action": "관망 (진입 비권장)",
        "entry": "26,600~28,000",
        "target": "29,400",
        "stop": "26,000",
        "reasoning": "거래량 부족. 진입 비권장.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "장비주지만 거래량 12만으로 관심 부족. AVGO 충격과 무관한 약세. 다른 장비주 대비 비선호.",
        "risk": "거래량 부족=유동성 리스크.",
        "supplement": "장비주 중 최하위 선호도.",
        "agreement": "동의"
      }
    },
    {
      "name": "리노공업",
      "ticker": "058470",
      "category": "소켓",
      "price": 94100,
      "change": -5.52,
      "rsi": 50.0,
      "support_1": 92800,
      "support_2": 88200,
      "resistance_1": 100000,
      "resistance_2": 105000,
      "volume_ratio": 1.0,
      "volume": 816528,
      "sma_5": 95900,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-5.52% 소켓 동반 하락. 92,800=1차 지지. PER 낮고 실적 안정적. ISC와 유사한 소켓업종. 거래량 82만=활발. 펀더멘탈 우량.",
        "action": "관망 (분할매수 검토)",
        "entry": "88,200~92,800",
        "target": "100,000",
        "stop": "87,000",
        "reasoning": "소켓주. 펀더멘탈 우량. 분할매수.",
        "elo": {
          "score": 1250,
          "wins": 2,
          "losses": 1,
          "total": 3,
          "accuracy": "66.7%",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "ISC와 유사하게 펀더멘탈 우량. AVGO 충격으로 과도한 낙폭. 92,800선 지지 확인 시 분할매수 유효.",
        "risk": "소켓업종 전체 약세시 동반 하락.",
        "supplement": "리노는 ISC와 쌍두마차. 방어주 성격.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "원익IPS",
      "ticker": "240810",
      "category": "장비",
      "price": 132700,
      "change": 4.32,
      "rsi": 50.0,
      "support_1": 97900,
      "support_2": 93000,
      "resistance_1": 127000,
      "resistance_2": 133500,
      "volume_ratio": 1.0,
      "volume": 3153461,
      "sma_5": 105000,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "+4.32% 장비주 반등 동참. RSI 62.5 중립권. 거래량 315만. SOXL 충격에 일부 영향. 월요일 -2~4% 조정 가능.",
        "action": "관망 (일부 익절 검토)",
        "entry": "125,000 이하",
        "target": "140,000",
        "stop": "118,000",
        "reasoning": "+4.32% 반등 성공. RSI 62=추격매수 금지.",
        "elo": {
          "score": 1300,
          "wins": 3,
          "losses": 1,
          "total": 4,
          "accuracy": "75.0%",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "PSK/HPSP보다 덜 올랐으니 차익실현 압력 상대적 적음. SOXL -24%면 장비주 전체 조정. 12만선 하락 시 분할매수 기회.",
        "risk": "장비주 5형제 일제 조정시 원익도 예외 아님.",
        "supplement": "원익 PER 낮아 밸류에이션 부담 적음. 조정 시 회복 빠를 가능성.",
        "agreement": "동의"
      }
    },
    {
      "name": "디아이",
      "ticker": "003160",
      "category": "장비",
      "price": 26750,
      "change": -4.29,
      "rsi": 50.0,
      "support_1": 26800,
      "support_2": 25400,
      "resistance_1": 26800,
      "resistance_2": 28100,
      "volume_ratio": 1.0,
      "volume": 302395,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                 차 분 기 보 고 서............................................................................................................................................1 【 대표이사 등의 확인 】...................................................................................................................",
      "ultra": {
        "analysis": "-4.29% 장비주 동반 하락. 26,800=지지선. 낙폭이 다른 장비주 대비 작음=상대적 방어력. 거래량 30만=보통.",
        "action": "관망",
        "entry": "25,400~26,800",
        "target": "28,100",
        "stop": "25,000",
        "reasoning": "장비주 중 낙폭 작음. 방어주.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "디아이는 장비주 중 낙폭 가장 작아 상대적 강세. AVGO 충격에도 방어력 입증. 추가 하락 시 매수 기회.",
        "risk": "장비주 전체 조정시 예외 없음.",
        "supplement": "디아이는 안정적 실적. 방어주.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "대덕전자",
      "ticker": "353200",
      "category": "PCB",
      "price": 152400,
      "change": -4.15,
      "rsi": 50.0,
      "support_1": 152500,
      "support_2": 145000,
      "resistance_1": 152500,
      "resistance_2": 160000,
      "volume_ratio": 1.0,
      "volume": 916464,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-4.15% PCB 동반 하락. 152,500=지지선. 낙폭 제한적=PCB 중 방어력 우수. 거래량 92만=활발. AVGO 충격 간접 영향.",
        "action": "관망",
        "entry": "145,000~152,500",
        "target": "160,000",
        "stop": "143,000",
        "reasoning": "PCB 방어주. 낙폭 제한적.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "대덕전자는 PCB 중 낙폭 가장 작음. 실적 안정성+방어력 인정. AVGO 충격 해소 후 반등시 유리.",
        "risk": "PCB 업종 약세 지속시 동반 하락.",
        "supplement": "PCB 최선호주. 조정시 분할매수.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "삼성전자우",
      "ticker": "005935",
      "category": "대장주",
      "price": 211000,
      "change": -4.09,
      "rsi": 50.0,
      "support_1": 202000,
      "support_2": 191500,
      "resistance_1": 241000,
      "resistance_2": 253000,
      "volume_ratio": 1.0,
      "volume": 5962640,
      "sma_5": 223500,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-4.09% 삼전 대비 낙폭 작음. 202,000=1차 지지. 우선주 특성상 보통주 대비 변동성 낮음. AVGO 충격에 동조화.",
        "action": "관망",
        "entry": "191,500~202,000",
        "target": "241,000",
        "stop": "190,000",
        "reasoning": "우선주. 보통주 대비 방어력.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "삼전우는 보통주 대비 낙폭 작아 상대적 안전. 배당 매력 있으나 AVGO 충격 해소 전까지 관망.",
        "risk": "보통주 추가 하락시 우선주도 동반.",
        "supplement": "삼전 바닥 확인 후 우선주 진입.",
        "agreement": "동의"
      }
    },
    {
      "name": "이오테크닉스",
      "ticker": "039030",
      "category": "장비",
      "price": 478000,
      "change": -3.63,
      "rsi": 50.0,
      "support_1": 432000,
      "support_2": 410500,
      "resistance_1": 496000,
      "resistance_2": 521000,
      "volume_ratio": 1.0,
      "volume": 206144,
      "sma_5": 453500,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목 차 분 기 보 고 서 ............................................................................................................................................1 【 대표이사 등의 확인 】 ...........................................................................................................................2 I. 회",
      "ultra": {
        "analysis": "-3.63% 장비주 중 유일한 하락. RSI 30.8 과매도 진입 직전. Pattern 7(이오-삼전 상관관계 붕괴) 지속 확인 중. 거래량 20만=관심 부족.",
        "action": "관망 (바닥 확인 후)",
        "entry": "450,000~465,000",
        "target": "495,000",
        "stop": "440,000",
        "reasoning": "박사님 최애종목. 장비주 반등에도 동참 못 함. RSI 30.8 바닥권.",
        "elo": {
          "score": 1150,
          "wins": 1,
          "losses": 3,
          "total": 4,
          "accuracy": "25.0%",
          "last_result": "",
          "agent_style": "supply",
          "agent_label": "수급",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "혼자 삐걱거리는 Pattern 7 지속. 오히려 금요일 장비주 대비 덜 올랐으니 월요일 하락 시 방어력 있을 수 있음. 저가 인식+반등 시 탄력적일 가능성. 거래량 20만=모멘텀 없음.",
        "risk": "Pattern 7 지속 시 장비주 반등에도 불참.",
        "supplement": "이오는 AVGO 충격과 무관한 독자 패턴. 바닥권 거래량 터지면 진입.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "케이씨텍",
      "ticker": "281820",
      "category": "장비",
      "price": 65300,
      "change": -3.55,
      "rsi": 50.0,
      "support_1": 65300,
      "support_2": 62000,
      "resistance_1": 65300,
      "resistance_2": 68600,
      "volume_ratio": 1.0,
      "volume": 147766,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "-3.55% 장비주 중 낙폭 작음. 65,300=지지선. 거래량 15만=낮음. 장비주 반등시 상대적 강세 기대.",
        "action": "관망",
        "entry": "62,000~65,300",
        "target": "68,600",
        "stop": "61,000",
        "reasoning": "장비주 중 방어력. 낙폭 작음.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "케이씨텍은 장비주 중 낙폭 최소. 실적 안정성+방어력. AVGO 충격 해소 후 반등시 68,600까지 회복 기대.",
        "risk": "거래량 15만=유동성 부족.",
        "supplement": "장비주 중 안전자산. 관망 유지.",
        "agreement": "동의"
      }
    },
    {
      "name": "테스",
      "ticker": "095610",
      "category": "장비",
      "price": 139200,
      "change": 2.43,
      "rsi": 50.0,
      "support_1": 139000,
      "support_2": 132000,
      "resistance_1": 139000,
      "resistance_2": 146000,
      "volume_ratio": 1.0,
      "volume": 1107080,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "+2.43% 장비주 반등 동참. RSI 50 기준 상승. 거래량 111만=활발. SOXL -24% 충격으로 월요일 조정 가능. 139,000선 방어 관건.",
        "action": "관망 (일부 익절 검토)",
        "entry": "—",
        "target": "146,000",
        "stop": "132,000",
        "reasoning": "+2.43% 상승. SOXL 충격에 조정 가능.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "PSK/HPSP만큼 오르지 않아 차익실현 압력 적음. 그러나 장비주 5형제는 월요일 일제 조정 가능. 139,000선 이탈 시 손절.",
        "risk": "SOXL -24%=장비주 조정 불가피.",
        "supplement": "테스는 장비주 중 중립. 익절/관망.",
        "agreement": "부분 동의"
      }
    },
    {
      "name": "DB하이텍",
      "ticker": "000990",
      "category": "파운드리",
      "price": 173800,
      "change": -1.47,
      "rsi": 50.0,
      "support_1": 174000,
      "support_2": 165000,
      "resistance_1": 174000,
      "resistance_2": 182500,
      "volume_ratio": 1.0,
      "volume": 538155,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                 차 분 기 보 고 서............................................................................................................................................1 【 대표이사 등의 확인 】...................................................................................................................",
      "ultra": {
        "analysis": "-1.47% 파운드리 동반 약세. 174,000=지지선. 낙폭 매우 제한적=방어력 우수. AVGO 충격과 파운드리 연관성 낮음.",
        "action": "관망",
        "entry": "165,000~174,000",
        "target": "182,500",
        "stop": "163,000",
        "reasoning": "파운드리. AVGO와 무관. 방어주.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "파운드리는 AVGO 충격과 무관. DB하이텍은 낙폭 최소로 방어력 입증. 174,000선 지지 시 안정적.",
        "risk": "파운드리 업황 둔화시 타격.",
        "supplement": "파운드리는 반도체 다운스트림. 안전.",
        "agreement": "동의"
      }
    },
    {
      "name": "유진테크",
      "ticker": "084370",
      "category": "장비",
      "price": 156900,
      "change": 0.77,
      "rsi": 50.0,
      "support_1": 157000,
      "support_2": 149000,
      "resistance_1": 157000,
      "resistance_2": 164500,
      "volume_ratio": 1.0,
      "volume": 473525,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "",
      "ultra": {
        "analysis": "+0.77% 장비주 보합권. 157,000=현재가=지지선. 거래량 47만=보통. SOXL -24%로 월요일 조정 가능. 방어력 테스트.",
        "action": "관망",
        "entry": "—",
        "target": "164,500",
        "stop": "149,000",
        "reasoning": "보합권. SOXL 충격에 관망.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "fund",
          "agent_label": "펀더멘탈",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "유진테크는 장비주 중 가장 약한 반등(+0.77%). 관심 부족 신호. SOXL 충격으로 월요일 -3~5% 가능.",
        "risk": "장비주 5형제 중 최약체. 추가 하락.",
        "supplement": "유진은 장비주 중 관심도 낮음. 패스.",
        "agreement": "동의"
      }
    },
    {
      "name": "코미코",
      "ticker": "183490",
      "category": "부품정비",
      "price": 990,
      "change": 0,
      "rsi": 50.0,
      "support_1": 990,
      "support_2": 940,
      "resistance_1": 990,
      "resistance_2": 1040,
      "volume_ratio": 1.0,
      "volume": 0,
      "sma_5": null,
      "sma_10": null,
      "sma_20": null,
      "quarterly_summary": "목                 차 분 기 보 고 서............................................................................................................................................1 【 대표이사 등의 확인 】...................................................................................................................",
      "ultra": {
        "analysis": "0% 보합. 거래량 0=거래 없음. 990원=지지선. 사실상 유동성 제로. 투자 비권장.",
        "action": "관망 (진입 비권장)",
        "entry": "—",
        "target": "—",
        "stop": "—",
        "reasoning": "거래량 0=유동성 제로. 비권장.",
        "elo": {
          "score": 1200,
          "wins": 0,
          "losses": 0,
          "total": 0,
          "accuracy": "--",
          "last_result": "",
          "agent_style": "tech",
          "agent_label": "테크니컬",
          "judge_history": []
        }
      },
      "hermes_deepseek": {
        "analysis": "거래량 0=사실상 거래 불가. 990원 최저가지만 유동성 리스크가 최대 단점. 투자 가치 없음.",
        "risk": "거래량 0=매수/매도 불가.",
        "supplement": "거래량 터지기 전까지 관망만.",
        "agreement": "동의"
      }
    }
  ]
};
